version: "3.7"

services:
  server:
    build: ./server
    command: npm start
    volumes:
    - .:/usr/app
    - /usr/app/node_modules
    ports:
    - "8000:8000"
    env_file:
    - ./server/.env
